### PR TITLE
Simplify mutex use

### LINKED ISSUE #111: Tally deadlocks if the reporter panics.
If AllocateCounter() below fails, , s.cm won't be unlocked and further calls to scope.Tagged() will deadlock.

```
func (s *scope) Counter(name string) Counter {
  name = s.sanitizer.Name(name)
  s.cm.RLock()
  val, ok := s.counters[name]
  s.cm.RUnlock()
  if !ok {
    s.cm.Lock()
    val, ok = s.counters[name]
    if !ok {
      var cachedCounter CachedCount
      if s.cachedReporter != nil {
        cachedCounter = s.cachedReporter.AllocateCounter(                                                                                                                                                                        
          s.fullyQualifiedName(name), s.tags,
        )
      }
      val = newCounter(cachedCounter)
      s.counters[name] = val
    }
    s.cm.Unlock()
  }
  return val
}
```

This is occurring with the prometheus reporter.

### PR DESCRIPTION
**Pull request by mway**
Fixes #111.

There's no real reason to attempt to hyper-optimize mutexes in this way; the cost of `defer` is negligible (for example, average counter allocation increased from 515ns to 580ns as part of this change) and the safety of deferring unlocks would be worth an even more substantial penalty.

Wherever this minor performance degradation would make a difference, metrics should be being cached anyway.

### CODE REVIEW

File: prometheus/reporter.go [hunk 1]
```diff
@@ -291,6 +291,18 @@ func NewReporter(opts Options) Reporter {
 	}
 	if opts.OnRegisterError == nil {
 		opts.OnRegisterError = func(err error) {
+			// n.b. Because our forked Prometheus client does not actually emit
```
Comment (jeffbean) [inline prometheus/reporter.go]: this seems to maybe warrant its own PR. lets not overload this diff with different concerns. Even though its to allow us to test i think since this is changing core behavior it should be its own diff.

Comment (mway) [reply prometheus/reporter.go]: I agree, but behavior isn't changing here - just the error that's being panicked. Users who provide their own `OnRegisterError` will see no difference as a result of this change.

The only difference that updating our Prom fork would do is allowing us to type switch on the error, and that comes at an unknown (but potentially high) cost of upgrading dependents' use of the Prom client, which I don't think is quite as valuable here. They're two distinct concerns, but one does not necessarily follow from the other.

Comment (mway) [reply prometheus/reporter.go]: (The same holds for would-be recoverers of this panic - this is a builtin error, so they will receive the same underlying error type via any `recover()` calls, modulo the additional (arguably more helpful) error message.

Comment (jeffbean) [reply prometheus/reporter.go]: ok, seems your case is reasonable.

File: prometheus/reporter_test.go [hunk 2]
```diff
@@ -358,6 +358,29 @@ func TestOnRegisterError(t *testing.T) {
...
+	})
+
+	r.AllocateCounter("foo", map[string]string{"foo": "bar"})
+	r.AllocateCounter("foo", map[string]string{"foo": "baz"}) // ok; same label names
+	r.AllocateCounter("foo", map[string]string{"bar": "qux"}) // errors; different label names
+	r.AllocateCounter("foo", map[string]string{
+		"bar":  "qux",
+		"zork": "derp",
+	}) // errors; different label names
+	r.AllocateCounter("foo", nil) // errors; different label names
```
Comment (jeffbean) [inline prometheus/reporter_test.go]: it's not obvious from `different label names ` why this is an error.

can we assert on an error string directly here?

Comment (mway) [reply prometheus/reporter_test.go]: sure! added some docs as well.

File: prometheus/reporter.go (hunk 1 above)
Comment (prashantv) [reply prometheus/reporter.go]: I'd still vote for this to go in a separate PR, given it's not related to mutex changes. It seems like a very independent change (definitely a good change, just not related to mutexes)

File: glide.yaml [hunk 3]
```diff
@@ -17,6 +17,8 @@ import:
   version: ^0.8.1
 - package: go.uber.org/atomic
   version: ^1
+- package: github.com/pkg/errors
```
Comment (prashantv) [inline glide.yaml]: can we move this out to a separate change, not really related to mutexes

File: scope.go [hunk 4]
```diff
@@ -269,16 +270,16 @@ func (s *scope) reportRegistryWithLock() {
...
 	}
-	s.registry.RUnlock()
 }
 
 func (s *scope) Counter(name string) Counter {
 	name = s.sanitizer.Name(name)
-	s.cm.RLock()
+
+	s.cm.Lock()
+	defer s.cm.Unlock()
```
Comment (prashantv) [inline scope.go]: This could have large performance implications, since an `RLock` allows multiple readers, while `Lock` only allows one reader.

I think it's common for callers to not hold a reference to a `Counter`, and to rely on this cache, and changing to a lock can significantly increase contention.

I'd suggest changing this to:
```go
func (s *scope) getCounter(name string) (Counter, bool) {
  s.cm.RLock()
  defer s.cm.RUnlock()

  val, ok := s.counters[name]
  return val, ok
}

func (s *scope) Counter(name string) Counter {
  if c, ok := s.getCounter(name); ok {
    return c
  }

  s.cm.Lock()
  defer s.cm.Unlock()

   if val,  ok := s.counters[name]; ok {
    return val
  }
  
  var cachedCounter CachedCount
  val = newCounter(cachedCounter)
  s.counters[name] = val
  return val
}
```

as a bonus, it significantly reduces the amount of nesting,
https://github.com/uber-go/guide/blob/master/style.md#reduce-nesting

same is true for `Gauge`, `Timer`, etc below

Comment (mway) [reply scope.go]: I explained in the description that benchmarks are negligibly impacted. Also, pedantically, `getX` is not a recommended Go naming convention:

> it's neither idiomatic nor necessary to put Get into the getter's name

(ref: [Effective Go](https://golang.org/doc/effective_go.html#Getters))

I'll make the change recommended here to minimize internal version churn, but let's put any additional changes into subsequent PRs. Sound fair?

File: glide.yaml (hunk 3 above)
Comment (mway) [reply glide.yaml]: I think this is a fair tradeoff for not implementing (however temporary) ad hoc error wrapping, e.g.:

```go
err = fmt.Errorf("something bad happened: %v", err)
```

is not conventionally used so much as:

```go
err = errors.WithMessage(err, "something bad happened")
```

(same with `errors.Wrap`, etc)

File: scope.go (hunk 4 above)
Comment (prashantv) [reply scope.go]: Is there benchmarks that test the contention caused by concurrency? I think we'll only see impact from benchmarks in that scenario.

Agree that lack of nesting can be done separately, just want to make sure we keep using `RLock` here, thanks

File: glide.yaml (hunk 3 above)
Comment (prashantv) [reply glide.yaml]: Agree, but I think that whole change (changing the error message) should be done separately since it isn't really related to the mutex simplification.

File: scope.go [hunk 5]
```diff
@@ -269,108 +270,155 @@ func (s *scope) reportRegistryWithLock() {
 		}
 		s.cachedReporter.Flush()
 	}
-	s.registry.RUnlock()
 }
 
 func (s *scope) Counter(name string) Counter {
+	if c, ok := s.counter(name); ok {
```
Comment (prashantv) [inline scope.go]: i think the sanitizer.Name needs to be called before we do this check here? maybe the argument name in `counter` should be called `sanitizedName` to make it clearer as well?

Comment (mway) [reply scope.go]: yeah, nice catch. thanks!

File: scope.go [hunk 6]
```diff
@@ -387,16 +431,13 @@ func (s *scope) subscope(prefix string, immutableTags map[string]string) Scope {
 	immutableTags = mergeRightTags(s.tags, immutableTags)
 	key := scopeRegistryKey(prefix, immutableTags)
 
-	s.registry.RLock()
+	s.registry.Lock()
```
Comment (prashantv) [inline scope.go]: we currently have `existing, ok := s.registry.subscopes[key]` twice below, which is probably a remnant of checking under rlock vs lock.

To avoid any performance difference, suggest doing the same thing as the counters etc by having the rlock check first in a separate function.

File: types.go [hunk 7]
```diff
@@ -28,6 +28,11 @@ import (
 
 // Scope is a namespace wrapper around a stats reporter, ensuring that
 // all emitted values have a given prefix or set of tags.
+//
```
Comment (prashantv) [inline types.go]: this probably belongs in the separate prob-related PR as well since it's not related to the mutexes

File: scope.go (hunk 6 above)
Comment (mway) [reply scope.go]: done!

File: types.go (hunk 7 above)
Comment (mway) [reply types.go]: 👍
